export const PRODUCTS = [
  {
    id: 'p-1',
    category: 'Clay Brick',
    brand: 'Wastsontown Brick',
    name: 'Bison - Red Matt Sanded Series',
    minPrice: 1.17,
    maxPrice: 1.19,
    stock: 8500,
    dateLead: new Date('2020-12-10'),
    dateEarliestPickup: new Date('2020-12-10'),
    material: 'Manufactured Stone',
    manufacturer: 'Arriscraft',
    otherSizes: ['2"', '11"', '8"', '5"'],
    status: 'ready',
  },
  {
    id: 'p-2',
    category: 'Mahogany',
    brand: 'Wastsontown Brick',
    name: 'Bison - Red Matt Sanded Series',
    minPrice: 1.17,
    maxPrice: 1.19,
    stock: 8500,
    dateLead: new Date('2020-12-10'),
    dateEarliestPickup: new Date('2020-12-10'),
    material: 'Manufactured Stone',
    manufacturer: 'Arriscraft',
    otherSizes: ['2"', '11"', '8"', '5"'],
    status: 'ready',
  },
  {
    id: 'p-3',
    category: 'Mahogany',
    brand: 'Wastsontown Brick',
    name: 'Bison - Red Matt Sanded Series',
    minPrice: 1.17,
    maxPrice: 1.19,
    stock: 8500,
    dateLead: new Date('2020-12-10'),
    dateEarliestPickup: new Date('2020-12-10'),
    material: 'Manufactured Stone',
    manufacturer: 'Arriscraft',
    otherSizes: ['2"', '11"', '8"', '5"'],
    status: 'ready',
  },
  {
    id: 'p-4',
    category: 'Mahogany',
    brand: 'Wastsontown Brick',
    name: 'Bison - Red Matt Sanded Series',
    minPrice: 1.17,
    maxPrice: 1.19,
    stock: 8500,
    dateLead: new Date('2020-12-10'),
    dateEarliestPickup: new Date('2020-12-10'),
    material: 'Manufactured Stone',
    manufacturer: 'Arriscraft',
    otherSizes: ['2"', '11"', '8"', '5"'],
    status: 'ready',
  },
  {
    id: 'p-5',
    category: 'Mahogany',
    brand: 'Wastsontown Brick',
    name: 'Bison - Red Matt Sanded Series',
    minPrice: 1.17,
    maxPrice: 1.19,
    stock: 8500,
    dateLead: new Date('2020-12-10'),
    dateEarliestPickup: new Date('2020-12-10'),
    material: 'Manufactured Stone',
    manufacturer: 'Arriscraft',
    otherSizes: ['2"', '11"', '8"', '5"'],
    status: 'ready',
  },
];
